"""empty message

Revision ID: 1318f65e321e
Revises: bc23bb550ac4
Create Date: 2022-02-03 16:38:39.535175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1318f65e321e'
down_revision = 'bc23bb550ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seo_data_for_linear_plots', sa.Column('data_source', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seo_data_for_linear_plots', 'data_source')
    # ### end Alembic commands ###
