"""empty message

Revision ID: 6265a6568cea
Revises: c885896a4cfd
Create Date: 2022-03-22 17:55:40.383212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6265a6568cea'
down_revision = 'c885896a4cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_collecting_report', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('data_collecting_report', sa.Column('value', sa.String(length=300), nullable=True))
    op.add_column('note', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'created')
    op.drop_column('data_collecting_report', 'value')
    op.drop_column('data_collecting_report', 'created')
    # ### end Alembic commands ###
