"""empty message

Revision ID: 831e077fe947
Revises: 1318f65e321e
Create Date: 2022-02-03 17:08:25.415914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831e077fe947'
down_revision = '1318f65e321e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('domain', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'domain')
    # ### end Alembic commands ###
