"""empty message

Revision ID: 9963d03a7322
Revises: 3be6635ae5e0
Create Date: 2022-01-25 19:19:57.307271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9963d03a7322'
down_revision = '3be6635ae5e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seo_data_for_linear_plots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=300), nullable=True),
    sa.Column('data_type', sa.String(length=300), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_name')
    )
    op.add_column('project', sa.Column('seranking_id', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('sitemap_path', sa.String(length=300), nullable=True))
    op.add_column('project', sa.Column('yandex_metrika_counter_id', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('yandex_webmaster_host', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'yandex_webmaster_host')
    op.drop_column('project', 'yandex_metrika_counter_id')
    op.drop_column('project', 'sitemap_path')
    op.drop_column('project', 'seranking_id')
    op.drop_table('seo_data_for_linear_plots')
    # ### end Alembic commands ###
