"""empty message

Revision ID: a54ae4b385ed
Revises: 9963d03a7322
Create Date: 2022-01-28 19:17:51.785650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54ae4b385ed'
down_revision = '9963d03a7322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('project_name', table_name='seo_data_for_linear_plots')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('project_name', 'seo_data_for_linear_plots', ['project_name'], unique=True)
    # ### end Alembic commands ###
