"""empty message

Revision ID: bc23bb550ac4
Revises: a54ae4b385ed
Create Date: 2022-02-01 22:38:43.186812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc23bb550ac4'
down_revision = 'a54ae4b385ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('second_sitemap_path', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'second_sitemap_path')
    # ### end Alembic commands ###
