"""empty message

Revision ID: c885896a4cfd
Revises: eeab0d3f11a5
Create Date: 2022-03-22 17:51:37.109807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c885896a4cfd'
down_revision = 'eeab0d3f11a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_collecting_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=300), nullable=True),
    sa.Column('report_name', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=300), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_collecting_report')
    # ### end Alembic commands ###
